import {useState} from 'react';
import {ArrowRight,MessageCircle,Monitor,Pause,RefreshCw,Sparkles,Volume2,VolumeX,Waves,Keyboard,X} from 'lucide-react';
import type {useConversation} from '../intelligence/useConversation';
type Props={conversation:ReturnType<typeof useConversation>;scan:(id:string)=>string;speaking:boolean;voiceEnabled:boolean;toggleVoice:()=>void;replay:()=>void;open:(view:'board'|'tasks'|'keyboard')=>void;draft:string;likelyChoice:string|null};
export function ConversationCanvas({conversation:c,scan,speaking,voiceEnabled,toggleVoice,replay,open,draft,likelyChoice}:Props){
 const [showGuide,setShowGuide]=useState(()=>{try{return localStorage.getItem('continuum.dashboardGuide')!=='hidden'}catch{return true}});
 const hideGuide=()=>{setShowGuide(false);try{localStorage.setItem('continuum.dashboardGuide','hidden')}catch{/* Private/storage-restricted sessions remain usable. */}};
 return <section className="conversation-canvas" aria-label="Conversation with Continuum">
  {showGuide&&<section className="usp-card" aria-label="What Continuum does for you"><div className="usp-head"><Sparkles size={18}/><strong>Your ability becomes your interface.</strong><button className="icon-button" aria-label="Hide this guide" onClick={hideGuide}><X size={16}/></button></div><p>Continuum learned the one movement or switch press that works best for you. Here is what you can do with it:</p><div className="usp-grid"><button onClick={()=>open('board')}><MessageCircle size={20}/><strong>Speak</strong><span>Choose a message and I will say it out loud for you.</span></button><button onClick={()=>open('keyboard')}><Keyboard size={20}/><strong>Type it out</strong><span>Spell a message letter by letter. I predict the next word.</span></button><button onClick={()=>open('tasks')}><Monitor size={20}/><strong>Computer help</strong><span>Ask me to open an app or website. You confirm before anything runs.</span></button></div><p className="usp-footnote">Inspired by the personalized systems used by people like Stephen Hawking — built to run on a laptop or phone you already own, not specialist hardware.</p></section>}
  <header className="companion-header"><div className={'companion-avatar '+(speaking?'is-speaking':'')} aria-hidden="true"><Waves size={36}/></div><div><h1>Continuum</h1><p>{speaking?'Speaking to you':c.pending?'Thinking on this device':'Your local AI assistant'}</p></div><button className={'icon-button'+scan('chat-voice')} aria-label={voiceEnabled?'Mute assistant voice':'Enable assistant voice'} onClick={toggleVoice}>{voiceEnabled?<Volume2 size={20}/>:<VolumeX size={20}/>}</button></header>
  <div className="conversation-thread" role="log" aria-label="Conversation history" aria-live="polite">{c.messages.slice(-6).map(message=><div className={'chat-message '+message.role} key={message.id}><span className="chat-role">{message.role==='assistant'?'CONTINUUM · AI':'YOU SELECTED'}</span><div className="chat-bubble">{message.content}</div></div>)}{c.pending&&<div className="chat-message assistant"><span className="chat-role">CONTINUUM</span><div className="chat-bubble thinking"><i/><i/><i/>Preparing a response…</div></div>}</div>
  {c.error&&<p role="alert" className="companion-status">{c.error}</p>}
  <div className="reply-options" aria-label="Suggested replies"><p>Select a reply with your configured movement or switch.</p>{c.choices.map((choice,index)=><button className={'reply-choice'+scan(`chat-${index}`)} key={choice} disabled={c.pending} onClick={()=>void c.send(choice)}>{choice}{choice===likelyChoice&&<span className="usual-badge">You usually say this</span>}<ArrowRight size={18}/></button>)}</div>
  {draft.trim()&&<div className="chat-draft"><span>YOUR COMPOSED MESSAGE</span><p>{draft}</p><button className={'button secondary'+scan('chat-send-draft')} disabled={c.pending} onClick={()=>void c.send(draft)}>Send to assistant<ArrowRight size={16}/></button></div>}
  <div className="companion-controls"><button className={'button secondary'+scan('chat-speak')} onClick={()=>open('board')}><MessageCircle size={18}/>Speak my message</button><button className={'button secondary'+scan('chat-tools')} onClick={()=>open('tasks')}><Monitor size={18}/>Computer actions</button><button className={'button secondary'+scan('chat-spell')} onClick={()=>open('keyboard')}><Keyboard size={18}/>Spell a reply</button>{c.pending?<button className={'text-button'+scan('chat-cancel')} onClick={c.cancel}><Pause size={15}/>Cancel response</button>:<button className={'text-button'+scan('chat-repeat')} onClick={replay}><RefreshCw size={15}/>Repeat assistant</button>}</div>
  <p className="companion-status">Assistant speech is separate from your approved messages. {c.model&&`${c.model} · ${((c.elapsedMs??0)/1000).toFixed(2)}s`}</p>
 </section>
}
